"""empty message

Revision ID: 71df3717e51a
Revises: cb000bf4d194
Create Date: 2022-12-08 12:29:31.548315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71df3717e51a'
down_revision = 'cb000bf4d194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owned_car', sa.Integer(), nullable=False))
        batch_op.drop_constraint('sales_owner_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_car_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['owned_car'], ['id'])
        batch_op.create_foreign_key(None, 'car', ['owner'], ['id'])
        batch_op.drop_column('car')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sales_car_fkey', 'car', ['car'], ['id'])
        batch_op.create_foreign_key('sales_owner_fkey', 'customer', ['owner'], ['id'])
        batch_op.drop_column('owned_car')

    # ### end Alembic commands ###
