"""empty message

Revision ID: 912c7d3b470c
Revises: 71df3717e51a
Create Date: 2022-12-08 12:32:03.440698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912c7d3b470c'
down_revision = '71df3717e51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('sales_owner_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_owned_car_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'car', ['car_id'], ['id'])
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])
        batch_op.drop_column('owner')
        batch_op.drop_column('owned_car')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owned_car', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sales_owned_car_fkey', 'customer', ['owned_car'], ['id'])
        batch_op.create_foreign_key('sales_owner_fkey', 'car', ['owner'], ['id'])
        batch_op.drop_column('customer_id')
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###
